# docker-compose with external network

# https://github.com/portainer/portainer/issues/2041

# https://docs.docker.com/compose/networking/


# docker network create kafka --attachable

version: "3"
services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    networks:
      - kafka
    restart: unless-stopped
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka:latest'
    networks:
      - kafka
    restart: unless-stopped
    user: root
    ports:
      - '9092:9092'
    volumes:
      - $PWD/kafka-persistence:/bitnami/kafka
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
networks:
  kafka:
      external: true